<a href="https://colab.research.google.com/github/SebastianPicazo/THC2/blob/main/Clase24deOctubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
print(arr[-1])

7


In [ ]:
print(arr[1:5:2])

[2 4]


In [ ]:
print(arr[::2])

[1 3 5 7]


In [ ]:
print(arr[::1])

[1 2 3 4 5 6 7]


In [ ]:
print(arr[:0])

[]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
print(arr[1:])

[[ 6  7  8  9 10]]


In [ ]:
print(arr[0:2,2])

[3 8]


In [ ]:
print(arr[0:3,2])

[3 8]


In [ ]:
print(arr[0:1,2])

[3]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
print(arr[0:1, 2:5]) #el primero son las filas y el segundo son las comulnas

[[3 4 5]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
import numpy as np

x=np.array([1,2,3])
y=np.array([4,5,6])
suma=x+y
print(f"La suma es {suma}")


La suma es [5 7 9]


In [ ]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
resta=x-y
print(f"La resta es {resta}")


La resta es [-3 -3 -3]


In [ ]:
mult=x*y
print(f"La mult es {mult}")

La mult es [ 4 10 18]


In [ ]:
div=x/y
print(f"La div es {div}")

La div es [0.25 0.4  0.5 ]


In [ ]:
print(f"Número pi={np.pi}")

Número pi=3.141592653589793


In [ ]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
print(f"Los senos {seno}")
print(f"De los angulos {angulos}")

Los senos [0.0000000e+00 1.0000000e+00 1.2246468e-16]
De los angulos [0.         1.57079633 3.14159265]


In [ ]:
angulos=np.array([0,np.pi/2,np.pi])
coseno=np.cos(angulos)
print(f"Los cosenos {coseno}")
print(f"De los angulos {angulos}")

Los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
De los angulos [0.         1.57079633 3.14159265]


In [ ]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [ ]:
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
x.reshape(-1,1).shape

(8, 1)

In [ ]:
x=np.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.random.uniform(0,1,6)

array([0.01172359, 0.76087371, 0.13104118, 0.54622202, 0.97359915,
       0.87184662])

In [ ]:
np.random.randint(0,10,size=3)

array([3, 3, 5])

In [ ]:
x=np.array(list(range(11)))
numero_obj=int(input("Coloque un numero del 1 al 10, para que el programa lo adivine"))
intentos=0
while True:
  intento=np.random.randint(0,10,size=1)
  intentos +=1
      if intento == numero_obj
      print("Tu numero es"{intento})
      else
      print("La maquina no adivino tu numero")

IndentationError: ignored